version: '3'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=dev_db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d dev_db"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  #Nest JS app
  api-1:
    extends:
      file: docker-compose.base.yml
      service: nx-app-base
    command: yarn api-1:dev:docker
    ports:
      - 3000:3000 # API Entry port
      - 4311:4311 # Server Debugging port
    environment:
      - DB_SOURCE=postgresql://root:secret@postgres:5432/dev_db?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  mono-node-modules: null